import * as XLSX from 'xlsx';

const fileName = 'test.xlsx';

const data = [
    {
        "_id": "62ed54b974bae0fff6aef275",
        "ID": 1,
        "NOMBRE_APELLIDO": "Jaime Bozo",
        "CEDULA": 5831725,
        "TELEFONO": 4127512533,
        "TALLER": "SALSA-PASTAS",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef27b",
        "ID": 4,
        "NOMBRE_APELLIDO": "Deiver Flores",
        "CEDULA": 30199013,
        "TELEFONO": 4126516326,
        "TALLER": "SALSA-PASTAS",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef27f",
        "ID": 6,
        "NOMBRE_APELLIDO": "Jose Mauricio Urdaneta",
        "CEDULA": 16609814,
        "TELEFONO": 4146133729,
        "TALLER": "SALSA-PASTAS",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef281",
        "ID": 7,
        "NOMBRE_APELLIDO": "Mariel Torres",
        "CEDULA": 7856291,
        "TELEFONO": 4246363080,
        "TALLER": "POSTRES-LIGEROS",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef277",
        "ID": 2,
        "NOMBRE_APELLIDO": "Maria Marin",
        "CEDULA": 16427674,
        "TELEFONO": 4246620091,
        "TALLER": "SALSA-PASTAS",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef279",
        "ID": 3,
        "NOMBRE_APELLIDO": "Delvis Soto",
        "CEDULA": 12455722,
        "TELEFONO": 4126931236,
        "TALLER": "SALSA-PASTAS",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef28d",
        "ID": 13,
        "NOMBRE_APELLIDO": "Soray Gonzalez",
        "CEDULA": 16918219,
        "TELEFONO": 4120328761,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef28f",
        "ID": 14,
        "NOMBRE_APELLIDO": "Lizardo Hernandez",
        "CEDULA": 13623953,
        "TELEFONO": 4146848639,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef291",
        "ID": 15,
        "NOMBRE_APELLIDO": "Joel Rodriguez",
        "CEDULA": 16981851,
        "TELEFONO": 4146663711,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef297",
        "ID": 18,
        "NOMBRE_APELLIDO": "Jesus Daniel Cassanova",
        "CEDULA": 31035821,
        "TELEFONO": 4149602465,
        "TALLER": "TALLER-PIZZERIA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef299",
        "ID": 19,
        "NOMBRE_APELLIDO": "Mariangel Nava Vidal",
        "CEDULA": 31337266,
        "TELEFONO": 4123935109,
        "TALLER": "TALLER-PIZZERIA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef29b",
        "ID": 20,
        "NOMBRE_APELLIDO": "Beiker Mengual",
        "CEDULA": 31021036,
        "TELEFONO": 4268677554,
        "TALLER": "TALLER-PIZZERIA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef29d",
        "ID": 21,
        "NOMBRE_APELLIDO": "Reinaldo Fernandez",
        "CEDULA": 10436929,
        "TELEFONO": 4146916453,
        "TALLER": "TALLER-PIZZERIA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef29f",
        "ID": 22,
        "NOMBRE_APELLIDO": "Johanna Sanchez",
        "CEDULA": 13511924,
        "TELEFONO": 4246290527,
        "TALLER": "TALLER-PIZZERIA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef2a1",
        "ID": 23,
        "NOMBRE_APELLIDO": "Jeseli Urdaneta",
        "CEDULA": 14631674,
        "TELEFONO": 4140688928,
        "TALLER": "TALLER-PIZZERIA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef2a5",
        "ID": 25,
        "NOMBRE_APELLIDO": "Agustin Barrios",
        "CEDULA": 15052830,
        "TELEFONO": 4146791261,
        "TALLER": "BARISMO",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef2a7",
        "ID": 26,
        "NOMBRE_APELLIDO": "Olasco Borquez",
        "CEDULA": 23857976,
        "TELEFONO": 4146004918,
        "TALLER": "PANADERIA-COMERCIAL",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef2ab",
        "ID": 28,
        "NOMBRE_APELLIDO": "Geiddy Sanchez",
        "CEDULA": 12513767,
        "TELEFONO": 4149663231,
        "TALLER": "PANADERIA-COMERCIAL",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef2b1",
        "ID": 31,
        "NOMBRE_APELLIDO": "Dagny Hernandez",
        "CEDULA": 14458891,
        "TELEFONO": 4166607084,
        "TALLER": "PANADERIA-COMERCIAL",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef2a3",
        "ID": 24,
        "NOMBRE_APELLIDO": "Carlos Palfitt",
        "CEDULA": 29579157,
        "TELEFONO": 4126930370,
        "TALLER": "TALLER-PIZZERIA",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62ed54b974bae0fff6aef2a9",
        "ID": 27,
        "NOMBRE_APELLIDO": "Ivonne Aldana",
        "CEDULA": 7625809,
        "TELEFONO": 4246458201,
        "TALLER": "PANADERIA-COMERCIAL",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "FASE": 2,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f0ff8ba2b6f2acbcafe09a",
        "ID": 79,
        "NOMBRE_APELLIDO": "Ana Andrade",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "CORREO": "",
        "TALLER": "REPOSTERIA",
        "FASE": 1,
        "GRUPO": "D",
        "CEDULA": 0,
        "N_PLANILLA": 0,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f0ff8ba2b6f2acbcafe0a6",
        "ID": 85,
        "NOMBRE_APELLIDO": "Carol Olivarez",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "FECHA_DE_NACIMIENTO": "1989-11-22T04:00:40.000Z",
        "SABE_LEER": "si",
        "CEDULA": 19837256,
        "TELEFONO": 4246147842,
        "TALLER": "REPOSTERIA",
        "FASE": 1,
        "GRUPO": "D",
        "N_PLANILLA": 0,
        "PROFESION": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f0ff8ba2b6f2acbcafe0a8",
        "ID": 86,
        "NOMBRE_APELLIDO": "Irayda Ortega",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "FECHA_DE_NACIMIENTO": "1956-04-06T04:30:40.000Z",
        "SABE_LEER": "si",
        "CEDULA": 4161244,
        "TELEFONO": 4121076712,
        "CORREO": "",
        "TALLER": "REPOSTERIA",
        "FASE": 1,
        "GRUPO": "D",
        "N_PLANILLA": 0,
        "PROFESION": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a4035f",
        "ID": 27,
        "NOMBRE_APELLIDO": "Yois Montrel",
        "CEDULA": 14631367,
        "TELEFONO": 4246246621,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a40369",
        "ID": 32,
        "NOMBRE_APELLIDO": "Doubraska Bento",
        "CEDULA": 9787143,
        "TELEFONO": 4143614327,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a40365",
        "ID": 30,
        "NOMBRE_APELLIDO": "Marianela Parra",
        "CEDULA": 9774867,
        "TELEFONO": 4246269315,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a4036b",
        "ID": 33,
        "NOMBRE_APELLIDO": "Marybel Colina",
        "CEDULA": 9114631,
        "TELEFONO": 4146333629,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a4036d",
        "ID": 34,
        "NOMBRE_APELLIDO": "Angel Vera",
        "CEDULA": 27763615,
        "TELEFONO": 4149618443,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a4036f",
        "ID": 35,
        "NOMBRE_APELLIDO": "Jenifer Rodriguez",
        "CEDULA": 30309850,
        "TELEFONO": 4128748688,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a40371",
        "ID": 36,
        "NOMBRE_APELLIDO": "Alberto Valbuena",
        "CEDULA": 6831339,
        "TELEFONO": 4246986100,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a40373",
        "ID": 37,
        "NOMBRE_APELLIDO": "Jesibel Rios",
        "CEDULA": 31071326,
        "TELEFONO": 4146620180,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a40375",
        "ID": 38,
        "NOMBRE_APELLIDO": "Hugo Barboza",
        "CEDULA": 13660220,
        "TELEFONO": 4146504830,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a40377",
        "ID": 39,
        "NOMBRE_APELLIDO": "Jenssel Gonzales",
        "CEDULA": 13758354,
        "TELEFONO": 4126520670,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a40379",
        "ID": 40,
        "NOMBRE_APELLIDO": "Liz Briceño",
        "CEDULA": 18395771,
        "TELEFONO": 4149687367,
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "C",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f103ccac9a92e577a403a7",
        "ID": 63,
        "NOMBRE_APELLIDO": "Hilde Soto",
        "CEDULA": 7827332,
        "TELEFONO": 4146349937,
        "CORREO": "",
        "TALLER": "PANADERIA-COMERCIAL",
        "FASE": 1,
        "GRUPO": "D",
        "N_PLANILLA": 0,
        "ESTADO": "",
        "CIUDAD": "",
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f12e5f39e94e7131e2c569",
        "ID": 41,
        "NOMBRE_APELLIDO": "Kely Mora",
        "ESTADO": "ZULIA",
        "CIUDAD": "MARACAIBO",
        "CEDULA": 25381452,
        "CORREO": "",
        "TELEFONO": 4123642218,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "MUNICIPIO": "",
        "FASE": 7,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f12e5f39e94e7131e2c56b",
        "ID": 42,
        "NOMBRE_APELLIDO": "Pablo Torres",
        "ESTADO": "ZULIA",
        "CIUDAD": "MARACAIBO",
        "CEDULA": 10447625,
        "CORREO": "",
        "TELEFONO": 4246113006,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "MUNICIPIO": "",
        "FASE": 7,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f12e5f39e94e7131e2c56d",
        "ID": 43,
        "NOMBRE_APELLIDO": "Jadira Odoño",
        "ESTADO": "ZULIA",
        "CIUDAD": "MARACAIBO",
        "CEDULA": 10426021,
        "CORREO": "",
        "TELEFONO": 4146239725,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "MUNICIPIO": "",
        "FASE": 7,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f12e5f39e94e7131e2c571",
        "ID": 45,
        "NOMBRE_APELLIDO": "Daniel Garcia",
        "ESTADO": "ZULIA",
        "CIUDAD": "MARACAIBO",
        "CEDULA": 26240981,
        "CORREO": "",
        "TELEFONO": 4127713874,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "MUNICIPIO": "",
        "FASE": 7,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f12e5f39e94e7131e2c56f",
        "ID": 44,
        "NOMBRE_APELLIDO": "yorwin peña",
        "ESTADO": "ZULIA",
        "CIUDAD": "MARACAIBO",
        "CEDULA": 15409089,
        "CORREO": "",
        "TELEFONO": 4126816361,
        "TALLER": "COMIDA-RAPIDA",
        "N_PLANILLA": 0,
        "MUNICIPIO": "",
        "FASE": 7,
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    },
    {
        "_id": "62f2594922e984ff65d5b0de",
        "ID": 57,
        "NOMBRE_APELLIDO": "wilfredo Medina",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "SABE_LEER": "Si",
        "TALLER": "REPOSTERIA",
        "FASE": 8,
        "CEDULA": 0,
        "N_PLANILLA": 0,
        "MUNICIPIO": "",
        "PROFESION": "",
        "FECHA_DE_NACIMIENTO": "",
        "CORREO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "ATTENDED": true,
        "COMPLETE": true
    }
]

/** 
 * 
 * '1': 180,
  '2': 194,
  '3': 234,
  '4': 267,
  '5': 186,
  '6': 287,
  '7': 152,
*/

const workSheet = XLSX.utils.json_to_sheet(data);
const workBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workBook, workSheet, "Sheet 1");
XLSX.writeFile(workBook, "export/exportwithouplanilla42.xlsx");