import * as XLSX from 'xlsx';

const fileName = 'test.xlsx';

const data = [
    {
        "_id": "62f108515089e6c539c17696",
        "ID": 1,
        "NOMBRE_APELLIDO": "JENNY MORALES",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CACIQUE MARA",
        "FECHA_DE_NACIMIENTO": "1981-11-20T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "GEOLOLA",
        "DIRECCION": "SECTOR CAÑADA HONDA RESID VISOCA TORRE MARIA AP 5D",
        "CEDULA": 14833824,
        "CORREO": "jennygeo93@gmail.com",
        "TELEFONO": "0412-6626499",
        "N_PLANILLA": 2209,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c1769c",
        "ID": 4,
        "NOMBRE_APELLIDO": "ANDRY GONZALEZ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "COQUIVACOA",
        "FECHA_DE_NACIMIENTO": "1984-07-23T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "MAESTRO PANADERO",
        "DIRECCION": "AV 2 CALLE #2-61 ",
        "CEDULA": 17462384,
        "CORREO": "andri_jose@hotmail.com",
        "TELEFONO": "0412-6931754",
        "N_PLANILLA": 105,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c1769e",
        "ID": 5,
        "NOMBRE_APELLIDO": "YANIDEL PEÑA",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CACIQUE MARA",
        "FECHA_DE_NACIMIENTO": "1982-09-10T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "TSU EN ADMINISTRACION",
        "DIRECCION": "SECTOR SOCORRO CALLE 96F CASA 19C-42",
        "CEDULA": 16493118,
        "CORREO": "yspuyspu@gmail.com",
        "TELEFONO": "0412-0650259",
        "N_PLANILLA": 220,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176a0",
        "ID": 6,
        "NOMBRE_APELLIDO": "YORGENIS MARQUEZ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "SAN FRANCISCO",
        "MUNICIPIO": "SAN FRANCISCO",
        "PARROQUIA": "FRANCISCO OCHOA",
        "FECHA_DE_NACIMIENTO": "2001-12-01T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ESTUDIANTE",
        "DIRECCION": "SIERRA MAESTRA CALLE 199",
        "CEDULA": 28467033,
        "CORREO": "yorgenismarquez79@gmail.com",
        "TELEFONO": "0424-6796379",
        "N_PLANILLA": 229,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176a2",
        "ID": 7,
        "NOMBRE_APELLIDO": "LIGIA MOSQUERA",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "COQUIVACOA",
        "FECHA_DE_NACIMIENTO": "1991-09-01T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "LCDA EN RRHH",
        "DIRECCION": "18 DE OCTUBRE AV 2 4G CASA #1-96",
        "CEDULA": 19766728,
        "CORREO": "mosquera2541@gmail.com",
        "TELEFONO": "0424-6536092",
        "N_PLANILLA": 233,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c17698",
        "ID": 2,
        "NOMBRE_APELLIDO": "ELVIN VILLALOBOS ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "IDELFONSO VASQUEZ",
        "FECHA_DE_NACIMIENTO": "1976-02-14T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "SUPERVISOR DE OPERACIONES",
        "DIRECCION": "CALLE 59A CASA #71A-111 URB CIUDADELA FARIA",
        "CEDULA": 12868701,
        "CORREO": "villalobosez@gmail.com",
        "TELEFONO": "0412-7889803",
        "N_PLANILLA": 16,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c1769a",
        "ID": 3,
        "NOMBRE_APELLIDO": "REINE SERGES",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "COQUIVACOA",
        "FECHA_DE_NACIMIENTO": "1986-01-06T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ODONTOLOGA",
        "DIRECCION": "AV 8 CON CALLE F URB IRAMA CASA 8-07",
        "CEDULA": 19679947,
        "CORREO": "drareinaserges@gmail.com",
        "TELEFONO": "0414-9658378",
        "N_PLANILLA": 57,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176a8",
        "ID": 10,
        "NOMBRE_APELLIDO": "SERBEIRA CARDENAS ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "OLEGARIO VILLALOBOS",
        "FECHA_DE_NACIMIENTO": "1978-09-04T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "AMA DE CASA",
        "DIRECCION": "AV 11F CON 11H CALLE 59 #59-02",
        "CEDULA": 15583712,
        "CORREO": "genesish@hotmail.com",
        "TELEFONO": "0414-9625084",
        "N_PLANILLA": 424,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176aa",
        "ID": 11,
        "NOMBRE_APELLIDO": "NERIO FERRER",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CARACCIOLO",
        "FECHA_DE_NACIMIENTO": "1978-10-13T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ABOGADO",
        "DIRECCION": "B/ LA VICTORIA AV65A CALLE 74 CASA 65A-07",
        "CEDULA": 15009703,
        "CORREO": "abognerioferrer@hotmail.com",
        "TELEFONO": "0426-4672999",
        "N_PLANILLA": 521,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176ac",
        "ID": 12,
        "NOMBRE_APELLIDO": "ADALBERTO LEDEZMA",
        "ESTADO": "ZULIA ",
        "CIUDAD": "SAN FRANCISCO",
        "MUNICIPIO": "SAN FRANCISCO",
        "PARROQUIA": "DOMITILA FLORES",
        "FECHA_DE_NACIMIENTO": "1989-08-22T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "BACHILLER",
        "DIRECCION": "B/ LA POLAR",
        "CEDULA": 18823740,
        "CORREO": "adalberto_2017@gmail.com",
        "TELEFONO": "0424-6195348",
        "N_PLANILLA": 648,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176ae",
        "ID": 13,
        "NOMBRE_APELLIDO": "YELISBETH LUENGO ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARA ",
        "MUNICIPIO": "MARA ",
        "PARROQUIA": "RICAURTE",
        "FECHA_DE_NACIMIENTO": "1996-11-02T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "AMA DE CASA",
        "DIRECCION": "SECTOR BALLESTERO",
        "CEDULA": 26017707,
        "CORREO": "luengolisbeth0401@gmail.com",
        "TELEFONO": "0414-0615017",
        "N_PLANILLA": 669,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176b0",
        "ID": 14,
        "NOMBRE_APELLIDO": "EUDOMAR RINCON",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARA",
        "MUNICIPIO": "MARA",
        "PARROQUIA": "TAMARE",
        "FECHA_DE_NACIMIENTO": "1990-12-22T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "DISTRIBUIDORA DE ALIMENTOS",
        "DIRECCION": "KM 28 VIA EL MOJAN SECTOR SIPISIPI",
        "CEDULA": 20945675,
        "CORREO": "eudomarrincon20@gmail.com",
        "TELEFONO": "0412-1739415",
        "N_PLANILLA": 679,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176b2",
        "ID": 15,
        "NOMBRE_APELLIDO": "JHONNY PERNIA ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "SAN FRANCISCO",
        "MUNICIPIO": "SAN FRANCISCO",
        "PARROQUIA": "SAN FRANCISCO",
        "FECHA_DE_NACIMIENTO": "1973-09-09T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "COCINERO",
        "DIRECCION": "B/ PRIMAVERA DEL SOL CASA 21 - 24",
        "CEDULA": 13563272,
        "CORREO": "perniajg@gmail.com",
        "TELEFONO": "0424-6439226",
        "N_PLANILLA": 699,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176b4",
        "ID": 16,
        "NOMBRE_APELLIDO": "CARLOS BARON",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "OLEGARIO VILLALOBOS",
        "FECHA_DE_NACIMIENTO": "1987-09-04T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "EMPLEADO LUZ",
        "DIRECCION": "CALLE 76 SECTOR CERROS DE MARIN",
        "CEDULA": 18662955,
        "CORREO": "baronkey4@gmail.com",
        "TELEFONO": "0412-0649739",
        "N_PLANILLA": 713,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176b6",
        "ID": 17,
        "NOMBRE_APELLIDO": "YONNY MEDINA ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "FRANCISCO EUGENIO B",
        "FECHA_DE_NACIMIENTO": "2000-06-03T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "BACHILLER",
        "DIRECCION": "URB ALTOS DEL SOL AMADA II",
        "CEDULA": 28391490,
        "CORREO": "yonnymedina112@gmail.com",
        "TELEFONO": "0412-7630992",
        "N_PLANILLA": 752,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176b8",
        "ID": 18,
        "NOMBRE_APELLIDO": "DANIELA ROMERO",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "SAN ISIDRO",
        "FECHA_DE_NACIMIENTO": "1993-12-17T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "AMA DE CASA",
        "DIRECCION": "VILLA SAN ISIDRO 4 ETAPA 01 ",
        "CEDULA": 25404115,
        "CORREO": "danielarincon_17@hotmail.com",
        "TELEFONO": "0416-5672336",
        "N_PLANILLA": 775,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176ba",
        "ID": 19,
        "NOMBRE_APELLIDO": "SONIA RANGEL ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "JUANA DE AVILA ",
        "FECHA_DE_NACIMIENTO": "1970-05-02T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "AMA DE CASA",
        "DIRECCION": "SECTOR TIERRA NEGRA EDIF SAGAPUR",
        "CEDULA": 10419542,
        "CORREO": "soniamrangel17@gmail.com",
        "TELEFONO": "0424-6204307",
        "N_PLANILLA": 778,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176bc",
        "ID": 20,
        "NOMBRE_APELLIDO": "MAZYARR MOSCOSO ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "FRANCISCO EUGENIO B",
        "FECHA_DE_NACIMIENTO": "1971-01-04T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "BIOANALISTA",
        "DIRECCION": "URB ALTOS DEL SOL AMADA SECTOR 2",
        "CEDULA": 9675581,
        "CORREO": "mazym98@gmail.com",
        "TELEFONO": "0416-6468683",
        "N_PLANILLA": 794,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176be",
        "ID": 21,
        "NOMBRE_APELLIDO": "MANUEL VIRLA",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CHIQUINQUIRA",
        "FECHA_DE_NACIMIENTO": "2004-06-28T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ESTUDIANTE",
        "DIRECCION": "CALLE 83 CON AV 13 ",
        "CEDULA": 30250840,
        "CORREO": "manuel2806@gmail.com",
        "TELEFONO": "0424-6668582",
        "N_PLANILLA": 811,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176c0",
        "ID": 22,
        "NOMBRE_APELLIDO": "DOUGMARYS ROSALES",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CARRACIOLO",
        "FECHA_DE_NACIMIENTO": "1987-01-11T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "BARISTA",
        "DIRECCION": "B/ PANAMERICANO AV 74B CASA 24-32",
        "CEDULA": 18428785,
        "CORREO": "ingdougmarys@gmail.com",
        "TELEFONO": "0414-6092133",
        "N_PLANILLA": 820,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176c2",
        "ID": 23,
        "NOMBRE_APELLIDO": "JEINNY MOLERO",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CACIQUE MARA",
        "FECHA_DE_NACIMIENTO": "1983-03-15T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ENFERMERA",
        "DIRECCION": "B/ SAN JOSE AV 36 CALLE 89 CASA 33-76",
        "CEDULA": 16986887,
        "CORREO": "paulasusej2001@gmail.com",
        "TELEFONO": "0412-1249737",
        "N_PLANILLA": 901,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176a4",
        "ID": 8,
        "NOMBRE_APELLIDO": "DARLENDYS PINEDA ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "LA CONCEPCION",
        "MUNICIPIO": "LA CONCEPCION",
        "PARROQUIA": "JESUS ENRIQUE L",
        "FECHA_DE_NACIMIENTO": "1987-03-28T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "BACHILLER",
        "DIRECCION": "LA CONCEPCION SECTOR LOS LIRIOS CALLE RIVAS CASA #443",
        "CEDULA": 18744776,
        "CORREO": "pinedadarlendys312@gmail.com",
        "TELEFONO": "0414-6748412",
        "N_PLANILLA": 321,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176a6",
        "ID": 9,
        "NOMBRE_APELLIDO": "ALIX MEDINA",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "COQUIVACOA",
        "FECHA_DE_NACIMIENTO": "1968-11-11T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ESTETICA",
        "DIRECCION": "18 DE OCTUBRE CALLE 6H AV 3 CASA 4-76",
        "CEDULA": 9708493,
        "CORREO": "josrey04@gmail.com",
        "TELEFONO": "0414-6989408",
        "N_PLANILLA": 184,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176c8",
        "ID": 26,
        "NOMBRE_APELLIDO": "WUESLADIA SALAZAR ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CACIQUE MARA",
        "FECHA_DE_NACIMIENTO": "1974-08-04T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "TSU EN RELACIONES INDUSTRIALES",
        "DIRECCION": "B/ SAN JOSE CALLE 92 B CASA 21B-56",
        "CEDULA": 11662954,
        "CORREO": "waleskabarrios@gmail.com",
        "TELEFONO": "0412-7880739",
        "N_PLANILLA": 1093,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176ca",
        "ID": 27,
        "NOMBRE_APELLIDO": "RAY CORDERO",
        "ESTADO": "ZULIA ",
        "CIUDAD": "SAN FRANCISCO",
        "MUNICIPIO": "SAN FRANCISCO",
        "PARROQUIA": "SAN FRANCISCO",
        "FECHA_DE_NACIMIENTO": "1964-06-04T04:30:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "OBRERO",
        "DIRECCION": "CALLE 177 PLAZA DEL SOL BLOQUE 12 AP 03-02",
        "CEDULA": 7818960,
        "CORREO": "raycordero409@hotmail.com",
        "TELEFONO": "0424-6481664",
        "N_PLANILLA": 1111,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176cc",
        "ID": 28,
        "NOMBRE_APELLIDO": "JAIRO CASANOVA",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "OLEGARIO VILLALOBOS",
        "FECHA_DE_NACIMIENTO": "1955-07-04T04:30:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "JUBILADO",
        "DIRECCION": "BELLA VISTA CALLE 64 #3D-107",
        "CEDULA": 5165180,
        "TELEFONO": "0414-6665559",
        "N_PLANILLA": 1134,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "CORREO": "",
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176ce",
        "ID": 29,
        "NOMBRE_APELLIDO": "DANIELA CALLE ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "JUANA DE AVILA ",
        "FECHA_DE_NACIMIENTO": "1998-10-29T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "SECRETARIA",
        "DIRECCION": "SAN JACINTO SECTOR 10 AV2 CALLE 4",
        "CEDULA": 27196007,
        "CORREO": "danielacalle2910@gmail.com",
        "TELEFONO": "0412-7681770",
        "N_PLANILLA": 1154,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176d0",
        "ID": 30,
        "NOMBRE_APELLIDO": "JAIRO LUBO ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CECILIO ACOSTA",
        "FECHA_DE_NACIMIENTO": "1970-08-01T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "DESEMPLEADO",
        "DIRECCION": "B/ PADRE DE LA PATRIA CASA 98C-27",
        "CEDULA": 9759128,
        "CORREO": "123458zzw@gmail.com",
        "TELEFONO": "0424-6168800",
        "N_PLANILLA": 1162,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176d2",
        "ID": 31,
        "NOMBRE_APELLIDO": "JESUS GONCALVES",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "IDELFONSO VASQUEZ",
        "FECHA_DE_NACIMIENTO": "2001-08-02T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ESTUDIANTE",
        "DIRECCION": "B/ AJONJOLI CALLE 30 AV 24 ",
        "CEDULA": 28272010,
        "CORREO": "goncalvesjesusbarrio@gmail.com",
        "TELEFONO": "0424-6451727",
        "N_PLANILLA": 1165,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176d4",
        "ID": 32,
        "NOMBRE_APELLIDO": "MARIANA HERNANDEZ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "RAUL LEONI",
        "FECHA_DE_NACIMIENTO": "1985-04-26T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ABOGADA",
        "DIRECCION": "LOS MODINES EDIF 17 PBC ",
        "CEDULA": 17087075,
        "CORREO": "marianahm26@gmail.com",
        "TELEFONO": "0414-6278228",
        "N_PLANILLA": 1175,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176d6",
        "ID": 33,
        "NOMBRE_APELLIDO": "ANA YEPES",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "RAUL LEONI",
        "FECHA_DE_NACIMIENTO": "1983-07-14T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ABOGADA",
        "DIRECCION": "LOS MODINES RAUL LEONI ",
        "CEDULA": 15600645,
        "TELEFONO": "0412-1291299",
        "N_PLANILLA": 1193,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "CORREO": "",
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176d8",
        "ID": 34,
        "NOMBRE_APELLIDO": "JOSE REYES",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "JUANA DE AVILA ",
        "FECHA_DE_NACIMIENTO": "1995-03-13T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "PANTRISTA",
        "DIRECCION": "SAN JACINTO SECTOR 10 CASA 03",
        "CEDULA": 23457669,
        "CORREO": "reyesh.jose@gmail.com",
        "TELEFONO": "0414-6063867",
        "N_PLANILLA": 1194,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176da",
        "ID": 35,
        "NOMBRE_APELLIDO": "ANA LOYO",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CACIQUE MARA",
        "FECHA_DE_NACIMIENTO": "1984-11-30T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "ABOGADA",
        "DIRECCION": "B/ SAN JOSE CALLE 92C #19D-89",
        "CEDULA": 16783833,
        "CORREO": "anachloyo@gmail.com",
        "TELEFONO": "0424-6700787",
        "N_PLANILLA": 1409,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176c4",
        "ID": 24,
        "NOMBRE_APELLIDO": "MARIA PAZ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "CHIQUINQUIRA",
        "FECHA_DE_NACIMIENTO": "2004-03-14T04:00:40.000Z",
        "SABE_LEER": "SI",
        "DIRECCION": "CALLE 91 CON AV 13",
        "CEDULA": 30952370,
        "CORREO": "mariavirginiapaz14@gmail.com",
        "TELEFONO": "0424-6723040",
        "N_PLANILLA": 909,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "PROFESION": "",
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f108515089e6c539c176c6",
        "ID": 25,
        "NOMBRE_APELLIDO": "CARLOS CORDERO ",
        "ESTADO": "ZULIA ",
        "CIUDAD": "MARACAIBO ",
        "MUNICIPIO": "MARACAIBO ",
        "PARROQUIA": "JUANA DE AVILA ",
        "FECHA_DE_NACIMIENTO": "1983-03-13T04:00:40.000Z",
        "SABE_LEER": "SI",
        "PROFESION": "BACHILLER",
        "DIRECCION": "SAN JACINTO SECTOR 4 CALLE 01 CASA 12",
        "CEDULA": 24956955,
        "CORREO": "carloscordero8384@gmail.com",
        "TELEFONO": "0424-6454765",
        "N_PLANILLA": 912,
        "TALLER": "ASISTENTE-COCINA",
        "FASE": 6,
        "GRUPO": "",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba323c",
        "ID": 1,
        "NOMBRE_APELLIDO": "LENIS LOPEZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "coquivacoa",
        "FECHA_DE_NACIMIENTO": "1964-11-17T04:30:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Abogada",
        "DIRECCION": "18 de octubre, calle H N°3-35",
        "CEDULA": 6171886,
        "CORREO": "lenislopez1@gmail.com",
        "TELEFONO": 4146136626,
        "N_PLANILLA": 1526,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3242",
        "ID": 4,
        "NOMBRE_APELLIDO": "DANIEL DORANTE",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "chiquinquira",
        "FECHA_DE_NACIMIENTO": "1995-03-12T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Enfermero",
        "DIRECCION": "Sector primero de mayo",
        "CEDULA": 25719736,
        "CORREO": "ddrad_12@hotmail.com",
        "TELEFONO": 4121863124,
        "N_PLANILLA": 1706,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3244",
        "ID": 5,
        "NOMBRE_APELLIDO": "ANAIS RIVAS",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "San francisco",
        "PARROQUIA": "domilita flores",
        "FECHA_DE_NACIMIENTO": "1995-09-16T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Enfermero",
        "DIRECCION": "Urb la popular sector 13",
        "CEDULA": 23763128,
        "CORREO": "anaisrivas70@gmail.com",
        "TELEFONO": 4146844200,
        "N_PLANILLA": 1743,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3246",
        "ID": 6,
        "NOMBRE_APELLIDO": "MARIA ESPINAL",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "coquivacoa",
        "FECHA_DE_NACIMIENTO": "2000-08-02T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Lic. Informatica",
        "DIRECCION": "villa camino real",
        "CEDULA": 27418323,
        "CORREO": "bloodymary_ve@hotmail.com",
        "TELEFONO": 4120787460,
        "N_PLANILLA": 1798,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3248",
        "ID": 7,
        "NOMBRE_APELLIDO": "MARCOS SOLER",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "San francisco",
        "PARROQUIA": "chiquinquira",
        "FECHA_DE_NACIMIENTO": "1978-11-23T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Ayudante integral",
        "DIRECCION": "sector el transito calle 95A",
        "CEDULA": 14657032,
        "CORREO": "marco23@hotmail.com",
        "TELEFONO": 4162631539,
        "N_PLANILLA": 1809,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba323e",
        "ID": 2,
        "NOMBRE_APELLIDO": "SHEYLAN PICON",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "carracciolo parra perez",
        "FECHA_DE_NACIMIENTO": "2000-04-07T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Estudiante",
        "DIRECCION": "los olivos",
        "CEDULA": 27105512,
        "CORREO": "sheylanpicon@gmail.com",
        "TELEFONO": 4146517376,
        "N_PLANILLA": 1681,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3240",
        "ID": 3,
        "NOMBRE_APELLIDO": "ANGELA ACOSTA",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "Santa lucia",
        "FECHA_DE_NACIMIENTO": "1982-01-03T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "oficios del hogar",
        "DIRECCION": "valle frio",
        "CEDULA": 15888031,
        "CORREO": "angeladelcarmenacosta@gmail.com",
        "TELEFONO": 4246934762,
        "N_PLANILLA": 1693,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba324e",
        "ID": 10,
        "NOMBRE_APELLIDO": "LISANDRA ANDRADE",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "cristo de aranza",
        "FECHA_DE_NACIMIENTO": "1994-05-02T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "oficios del hogar",
        "DIRECCION": "B/ ricardo aguirre av 25A N°117-50",
        "CEDULA": 25458015,
        "CORREO": "lisandradep@gmail.com",
        "TELEFONO": 4121666847,
        "N_PLANILLA": 2220,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3250",
        "ID": 11,
        "NOMBRE_APELLIDO": "RAUL GOMEZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "San francisco",
        "PARROQUIA": "juana de avila",
        "FECHA_DE_NACIMIENTO": "1997-08-22T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "programador",
        "DIRECCION": "urb san jacinto sector 8 vereda 6",
        "CEDULA": 26405851,
        "CORREO": "rauljgomez14@gmail.com",
        "TELEFONO": 4246612615,
        "N_PLANILLA": 2249,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3252",
        "ID": 12,
        "NOMBRE_APELLIDO": "ISAYE ORTIZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "los cortijos",
        "FECHA_DE_NACIMIENTO": "1999-10-26T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Estudiante",
        "DIRECCION": "Ciudadela rafael caldera av47M",
        "CEDULA": 27972985,
        "CORREO": "isayeortizdea@gmail.com",
        "TELEFONO": 4127752712,
        "N_PLANILLA": 2273,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3254",
        "ID": 13,
        "NOMBRE_APELLIDO": "DIEGO RINCON",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "manuel dfagnino",
        "FECHA_DE_NACIMIENTO": "1999-04-03T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "bachiller",
        "DIRECCION": "Sabaneta la mision ",
        "CEDULA": 26826482,
        "CORREO": "dfrg_@hotmail.com",
        "TELEFONO": 4141685196,
        "N_PLANILLA": 2468,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3256",
        "ID": 14,
        "NOMBRE_APELLIDO": "WENDY HERNANDEZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "idelfonso vasquez",
        "FECHA_DE_NACIMIENTO": "1986-01-04T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "asistente de salud",
        "DIRECCION": "B/ terepaima calle 41",
        "CEDULA": 18574073,
        "CORREO": "misencanto@hotmail.com",
        "TELEFONO": 4140691457,
        "N_PLANILLA": 2604,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3258",
        "ID": 15,
        "NOMBRE_APELLIDO": "VANESSA SERRANO",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "luis hurtado higuera",
        "FECHA_DE_NACIMIENTO": "2000-08-04T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Estudiante",
        "DIRECCION": "B/ integracion comunal",
        "CEDULA": 29546145,
        "CORREO": "vanessaserranorojas@gmial.com",
        "TELEFONO": 4140374610,
        "N_PLANILLA": 2610,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba325a",
        "ID": 16,
        "NOMBRE_APELLIDO": "OLGA PIRELA",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Mara",
        "PARROQUIA": "cacique mara",
        "FECHA_DE_NACIMIENTO": "1984-10-16T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Pastelera",
        "DIRECCION": "B/ san jose calle 92",
        "CEDULA": 16353863,
        "CORREO": "olgapirela16@outlook.es",
        "TELEFONO": 4146788977,
        "N_PLANILLA": 2656,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba325c",
        "ID": 17,
        "NOMBRE_APELLIDO": "HECMI CASTELLANO",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "raul leoni",
        "FECHA_DE_NACIMIENTO": "1987-08-01T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "abogada",
        "DIRECCION": "Residencia el alto edif amelia",
        "CEDULA": 18575642,
        "CORREO": "castellanohecmi@gmail.com",
        "TELEFONO": 4146216432,
        "N_PLANILLA": 2713,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba325e",
        "ID": 18,
        "NOMBRE_APELLIDO": "CAROLINA OCANDO",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "juana de avila",
        "FECHA_DE_NACIMIENTO": "1986-04-13T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "docente",
        "DIRECCION": "san jacinto sector 9",
        "CEDULA": 17669243,
        "CORREO": "carolina1304ocando@hotmail.com",
        "TELEFONO": 4146848400,
        "N_PLANILLA": 2831,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3260",
        "ID": 19,
        "NOMBRE_APELLIDO": "SAYIRA BRICEÑO ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "cecilio acosta",
        "FECHA_DE_NACIMIENTO": "15/28/1968",
        "SABE_LEER": "Si",
        "PROFESION": "cocinera",
        "DIRECCION": "calle 96F",
        "CEDULA": 8508407,
        "CORREO": "briceñosayira15@gmail.com",
        "TELEFONO": 4246152013,
        "N_PLANILLA": 2896,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3262",
        "ID": 20,
        "NOMBRE_APELLIDO": "LUIS GONZALEZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "FECHA_DE_NACIMIENTO": "1993-04-25T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "profesor de deporte",
        "DIRECCION": "los robles av 67 ",
        "CEDULA": 22477011,
        "CORREO": "luisgonlz@gmail.com",
        "TELEFONO": 4246723155,
        "N_PLANILLA": 2901,
        "FASE": 8,
        "PARROQUIA": "",
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3264",
        "ID": 21,
        "NOMBRE_APELLIDO": "YUSANDRY OCANDO",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "concepcion",
        "FECHA_DE_NACIMIENTO": "1981-09-25T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "oficios del hogar",
        "DIRECCION": "av principal sector el venao",
        "CEDULA": 14863330,
        "CORREO": "yusaocando@gmail.com",
        "TELEFONO": 4141655603,
        "N_PLANILLA": 2923,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3266",
        "ID": 22,
        "NOMBRE_APELLIDO": "LENIN RODRIGUEZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "maracaibo",
        "SABE_LEER": "Si",
        "PROFESION": "comerciante",
        "DIRECCION": "72 con 10 av residencia claret",
        "CEDULA": 9734700,
        "CORREO": "leninrodriguez1930@gmail.com",
        "TELEFONO": 4246974768,
        "N_PLANILLA": 2777,
        "FASE": 8,
        "FECHA_DE_NACIMIENTO": "",
        "PARROQUIA": "",
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba324c",
        "ID": 9,
        "NOMBRE_APELLIDO": "YARIBETH RUIZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "Francisco ochoa",
        "FECHA_DE_NACIMIENTO": "1992-11-05T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "oficios del hogar",
        "DIRECCION": "Sierra Maestra",
        "CEDULA": 20860663,
        "CORREO": "yari20beth@gmail.com",
        "TELEFONO": 4140615700,
        "N_PLANILLA": 1839,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba324a",
        "ID": 8,
        "NOMBRE_APELLIDO": "ANDY ARRIETA",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "cristo de aranza",
        "FECHA_DE_NACIMIENTO": "1994-09-30T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "cocinero",
        "DIRECCION": "av 19-C la pomona",
        "CEDULA": 25043827,
        "CORREO": "arrietaandy@hotmail.com",
        "TELEFONO": 4246656162,
        "N_PLANILLA": 1828,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba3268",
        "ID": 23,
        "NOMBRE_APELLIDO": "KENNETH DIAZ",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "San francisco",
        "PARROQUIA": "cristo de aranza",
        "FECHA_DE_NACIMIENTO": "1986-12-14T04:00:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "bachiller",
        "DIRECCION": "francisco mendoza calle 126D",
        "CEDULA": 17736434,
        "CORREO": "kennethdiaz069@gmail.com",
        "TELEFONO": 4146175404,
        "N_PLANILLA": 1960,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    },
    {
        "_id": "62f2770ba2d7898331ba326a",
        "ID": 24,
        "NOMBRE_APELLIDO": "JOSE TABORDA",
        "ESTADO": "Zulia",
        "CIUDAD": "Maracaibo",
        "MUNICIPIO": "Maracaibo",
        "PARROQUIA": "machiques",
        "FECHA_DE_NACIMIENTO": "1963-05-02T04:30:40.000Z",
        "SABE_LEER": "Si",
        "PROFESION": "Tecn. Superior en petroleo",
        "DIRECCION": "av libertador la paz",
        "CEDULA": 7768618,
        "CORREO": "cristoctaborda@hotmail.com",
        "TELEFONO": 4146670160,
        "N_PLANILLA": 2781,
        "FASE": 8,
        "GRUPO": "",
        "TALLER": "ASISTENTE-COCINA",
        "ATTENDED": false,
        "COMPLETE": false,
        "GP": "B"
    }
]

/** 
 * 
 * '1': 180,
  '2': 194,
  '3': 234,
  '4': 267,
  '5': 186,
  '6': 287,
  '7': 152,
*/

const workSheet = XLSX.utils.json_to_sheet(data);
const workBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workBook, workSheet, "Sheet 1");
XLSX.writeFile(workBook, "export/exportasitcocina.xlsx");