import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { render } from "react-dom";

import { editUser } from "../../lib/users";

const NotPlanilla = () => {
  const router = useRouter();
  const { slug } = router.query;

  const [user, setUser] = useState("");

  const [telephone, updateTelephone] = useState(0);

  const handleChange = (e) => {
    console.log(e.target.id);
    console.log(e.target.value)
    console.log(user[e.target.id])
  };

  useEffect(() => {
    let isSubscribed = false;

    const searchUserEdit = async (userci) => {
      const result = await editUser(parseInt(userci));

      if (!isSubscribed) {
        isSubscribed = true;
        setUser(result);
      }

      console.log(result);
    };

    searchUserEdit(slug).catch(console.error("error"));
  }, [slug]);

  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="min-h-full">
          <nav className="bg-gray-800">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center justify-between h-16">
                <div className="flex items-center">
                  <div className="flex-shrink-0">
                    <img
                      className="h-8 w-8"
                      src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg"
                      alt="Workflow"
                    />
                  </div>
                  <div className="hidden md:block">
                    <div className="ml-10 flex items-baseline space-x-4">
                      <a
                        href="#"
                        className="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
                        aria-current="page"
                      >
                        Dashboard
                      </a>
                    </div>
                  </div>
                </div>
                <div className="hidden md:block">
                  <div className="ml-4 flex items-center md:ml-6">
                    <button
                      type="button"
                      className="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                    >
                      <span className="sr-only">View notifications</span>

                      <svg
                        className="h-6 w-6"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth="2"
                        stroke="currentColor"
                        aria-hidden="true"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
                        />
                      </svg>
                    </button>
                  </div>
                </div>
                <div className="-mr-2 flex md:hidden">
                  <button
                    type="button"
                    className="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                    aria-controls="mobile-menu"
                    aria-expanded="false"
                  >
                    <span className="sr-only">Open main menu</span>

                    <svg
                      className="block h-6 w-6"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="2"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M4 6h16M4 12h16M4 18h16"
                      />
                    </svg>

                    <svg
                      className="hidden h-6 w-6"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="2"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M6 18L18 6M6 6l12 12"
                      />
                    </svg>
                  </button>
                </div>
              </div>
            </div>

            <div className="md:hidden" id="mobile-menu">
              <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                <a
                  href="#"
                  className="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"
                  aria-current="page"
                >
                  Dashboard
                </a>
              </div>
              <div className="pt-4 pb-3 border-t border-gray-700">
                <div className="flex items-center px-5">
                  <div className="flex-shrink-0">
                    <img
                      className="h-10 w-10 rounded-full"
                      src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                      alt=""
                    />
                  </div>
                  <div className="ml-3">
                    <div className="text-base font-medium leading-none text-white">
                      Tom Cook
                    </div>
                    <div className="text-sm font-medium leading-none text-gray-400">
                      tom@example.com
                    </div>
                  </div>
                  <button
                    type="button"
                    className="ml-auto bg-gray-800 flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                  >
                    <span className="sr-only">View notifications</span>

                    <svg
                      className="h-6 w-6"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="2"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
                      />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </nav>

          <header className="bg-white shadow">
            <div className=" max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
              <h1 className="text-3xl font-bold text-gray-900">
                Participante: <br />
                {user.NOMBRE_APELLIDO ? (
                  "xd"
                ) : (
                  <>
                    <span className="animate-pulse">Cargando...</span>
                  </>
                )}
              </h1>
            </div>
          </header>

          <main>
            <div>
              <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
                <form>
                  <div className="border-2 overflow-hidden sm:rounded-md">
                    <div className="px-4 py-5 bg-white sm:p-6">
                      <div className="px-4 sm:px-0 mb-5">
                        <h3 className="text-lg font-medium leading-6 text-gray-900">
                          Información personal
                        </h3>
                        <p className="mt-1 text-sm text-gray-600">
                          Información personal y confidencial del partipante,
                          tener precaución.
                        </p>
                      </div>
                      <div className="grid justify-center align-center grid-cols-6 gap-6">
                        <div
                          className={`${
                            user.NOMBRE_APELLIDO ? "" : "animate-pulse"
                          } col-span-6 sm:col-span-6 lg:col-span-2`}
                        >
                          <label
                            htmlFor="city"
                            className="block text-sm font-medium text-gray-700"
                          >
                            NOMBRE Y APELLIDO
                          </label>
                          <input
                            type="text"
                            name="city"
                            onChange={handleChange}
                            value={user.NOMBRE_APELLIDO}
                            id="NOMBRE_APELLIDO"
                            autoComplete="address-level2"
                            className=" mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>

                        <div
                          className={`${
                            user.CEDULA ? "" : "animate-pulse"
                          } col-span-6 sm:col-span-6 lg:col-span-2`}
                        >
                          <label
                            htmlFor="region"
                            className="block text-sm font-medium text-gray-700"
                          >
                            CÉDULA DE IDENTIDAD
                          </label>
                          <input
                            type="text"
                            name="region"
                            id="region"
                            value={user.CEDULA}
                            autoComplete="address-level1"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>

                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            FECHA DE NACIMIENTO
                          </label>

                          <input
                            type="text"
                            name="postal-code"
                            id="postal-code"
                            value="NO DISPONIBLE"
                            autoComplete="postal-code"
                            disabled
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 text-gray-200 rounded-md"
                          />
                        </div>
                        <div
                          className={`${
                            user.CORREO ? "" : "animate-pulse"
                          } col-span-6 sm:col-span-6 lg:col-span-2`}
                        >
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            CORREO
                          </label>
                          <input
                            type="text"
                            name="postal-code"
                            id="CORREO"
                            value={user.CORREO}
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div
                          className={`${
                            user.TELEFONO ? "" : "animate-pulse"
                          } col-span-6 sm:col-span-6 lg:col-span-2`}
                        >
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            TELEFONO
                          </label>
                          <input
                            type="text"
                            id="TELEFONO"
                            value={user.TELEFONO}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            DIRECCIÓN
                          </label>
                          <input
                            type="text"
                            name="postal-code"
                            id="DIRECCION"
                            value={user.DIRECCION}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            PARROQUIA
                          </label>
                          <input
                            type="text"
                            name="postal-code"
                            id="PARROQUIA"
                            value={user.PARROQUIA}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            CIUDAD
                          </label>
                          <input
                            type="text"
                            name="postal-code"
                            id="CIUDAD"
                            value={user.CIUDAD}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            MUNICIPIO
                          </label>
                          <input
                            type="text"
                            id="MUNICIPIO"
                            value={user.MUNICIPIO}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            ESTADO
                          </label>
                          <input
                            type="text"
                            id="ESTADO"
                            value={user.ESTADO}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                      </div>
                      <div className="hidden sm:block" aria-hidden="true">
                        <div className="py-5">
                          <div className="border-t border-gray-200"></div>
                        </div>
                      </div>
                      <div className="px-4 sm:px-0 mb-5">
                        <h3 className="text-lg font-medium leading-6 text-gray-900">
                          Información en el Programa
                        </h3>
                        <p className="mt-1 text-sm text-gray-600">
                          Información personal y confidencial del partipante,
                          tener precaución.
                        </p>
                      </div>
                      <div className="grid grid-cols-6 gap-6">
                        <div className="col-span-6 sm:col-span-6 lg:col-span-2">
                          <label
                            htmlFor="city"
                            className="block text-sm font-medium text-gray-700"
                          >
                            NÚMERO DE PLANILLA
                          </label>
                          <input
                            type="text"
                            name="city"
                            id="N_PLANILLA"
                            value={user.N_PLANILLA}
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="country"
                            className="block text-sm font-medium text-gray-700"
                          >
                            ¿ASISTIÓ?
                          </label>
                          <select
                            id="ATTENDED"
                            name="country"
                            autoComplete="country-name"
                            className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                          >
                            <option value={user.ATTENDED ? true : false}>
                              {user.ATTENDED ? "SI" : "NO"}
                            </option>
                            <option value={user.ATTENDED ? false : true}>
                              {user.ATTENDED ? "NO" : "SI"}
                            </option>
                          </select>
                        </div>

                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="country"
                            className="block text-sm font-medium text-gray-700"
                          >
                            ¿COMPLETÓ?
                          </label>
                          <select
                            id="complete"
                            className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                          >
                            <option value={user.COMPLETE ? true : false}>
                              {user.COMPLETE ? "SI" : "NO"}
                            </option>
                            <option value={user.COMPLETE ? false : true}>
                              {user.COMPLETE ? "NO" : "SI"}
                            </option>
                          </select>
                        </div>

                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="region"
                            className="block text-sm font-medium text-gray-700"
                          >
                            TALLER
                          </label>
                          <input
                            type="text"
                            name="region"
                            id="TALLER"
                            value={user.TALLER}
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>

                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            FASE
                          </label>
                          <input
                            type="text"
                            id="FASE"
                            value={user.FASE}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            GRUPO/SECCION
                          </label>
                          <input
                            type="text"
                            id="GRUPO"
                            value={user.GRUPO}
                            autoComplete="postal-code"
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                        <div className="col-span-6 sm:col-span-3 lg:col-span-2">
                          <label
                            htmlFor="postal-code"
                            className="block text-sm font-medium text-gray-700"
                          >
                            ORDEN
                          </label>
                          <input
                            type="text"
                            id="ORDEN"
                            value={user.ID}
                            className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                          />
                        </div>
                      </div>
                    </div>
                    <div className="px-4 py-3 bg-gray-50 text-right sm:px-6">
                      <button
                        type="submit"
                        className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                      >
                        Modificar
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </main>
        </div>
      </div>
    </>
  );
};

export default NotPlanilla;
