import Head from "next/head";

import { useState, useEffect } from "react";
import { searchUserWithInput } from "../lib/users";

const Filters = () => {
  const [filterSelect, setFilterSelect] = useState("ATTENDED");
  const [totalUsersNotPlanilla, settotalUsersNotPlanilla] = useState([]);

  const [filterCount, updateFilterCount] = useState(0);

  const searchButton = async () => {
    const filtereds = document.getElementById("filters");

    var whatSearching = "";
    var fSelect = filterSelect;

    if (filterSelect == "N_PLANILLA") {
      whatSearching = 0;
    }

    if (filterSelect == "CORREO") {
      whatSearching = "";
    }

    if (filterSelect == "PROFESION") {
      whatSearching = "";
    }

    if (filterSelect == "GRUPO") {
      whatSearching = "";
    }

    if (filterSelect == "PARROQUIA") {
      whatSearching = "";
    }

    if (filterSelect == "FASE") {
      whatSearching = 0;
    }

    if (filterSelect == "ATTENDED") {
      fSelect = "ATTENDED";
      whatSearching = true;
    }

    if (filterSelect == "NO-ATTENDED") {
      fSelect = "ATTENDED";
      whatSearching = false;
    }

    if (filterSelect == "COMPLETE") {
      fSelect = "COMPLETE";
      whatSearching = true;
    }

    if (filterSelect == "NO-COMPLETE") {
      fSelect = "COMPLETE";
      whatSearching = false;
    }

    if (filterSelect == "CEDULA") {
      fSelect = "CEDULA";
      whatSearching = 0;
    }

    const meme = await searchUserWithInput(fSelect, whatSearching);
    settotalUsersNotPlanilla((planilla) => [...meme]);

    updateFilterCount(meme.length);

    console.log("Busca", filtereds.value);
  };

  const handleChangeSelect = (e) => {
    setFilterSelect(e.target.value);
  };

  useEffect(() => {
    console.log(filterSelect);
  }, [filterSelect]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-full">
        <nav className="bg-gray-800">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between h-16">
              <div className="flex items-center">
                <div className="flex-shrink-0">
                  <img
                    className="h-8 w-8"
                    src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg"
                    alt="Workflow"
                  />
                </div>
                <div className="hidden md:block">
                  <div className="ml-10 flex items-baseline space-x-4">
                    <a
                      href="#"
                      className="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
                      aria-current="page"
                    >
                      Filters
                    </a>
                  </div>
                </div>
              </div>
              <div className="hidden md:block">
                <div className="ml-4 flex items-center md:ml-6">
                  <button
                    type="button"
                    className="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                  >
                    <span className="sr-only">View notifications</span>

                    <svg
                      className="h-6 w-6"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="2"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
                      />
                    </svg>
                  </button>
                </div>
              </div>
              <div className="-mr-2 flex md:hidden">
                <button
                  type="button"
                  className="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                  aria-controls="mobile-menu"
                  aria-expanded="false"
                >
                  <span className="sr-only">Open main menu</span>

                  <svg
                    className="block h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="2"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M4 6h16M4 12h16M4 18h16"
                    />
                  </svg>

                  <svg
                    className="hidden h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="2"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </div>

          <div className="md:hidden" id="mobile-menu">
            <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
              <a
                href="#"
                className="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"
                aria-current="page"
              >
                Filters
              </a>
            </div>
            <div className="pt-4 pb-3 border-t border-gray-700">
              <div className="flex items-center px-5">
                <div className="flex-shrink-0">
                  <img
                    className="h-10 w-10 rounded-full"
                    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    alt=""
                  />
                </div>
                <div className="ml-3">
                  <div className="text-base font-medium leading-none text-white">
                    Tom Cook
                  </div>
                  <div className="text-sm font-medium leading-none text-gray-400">
                    tom@example.com
                  </div>
                </div>
                <button
                  type="button"
                  className="ml-auto bg-gray-800 flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                >
                  <span className="sr-only">View notifications</span>

                  <svg
                    className="h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="2"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </nav>

        <header className="bg-white shadow">
          <div className=" max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 className="flex text-3xl font-bold text-gray-900">
              Filtración de participantes
            </h1>
            <div className="flex items-center space-x-2">
              <label
                htmlFor="country"
                className="block text-sm font-medium text-gray-700"
              >
                Filtrar por:
              </label>
              <select
                id="filters"
                onChange={handleChangeSelect}
                className="mt-1 w-80 py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              >
                <option value="ATTENDED">Asistieron</option>
                <option value="NO-ATTENDED">No asistieron</option>
                <option value="COMPLETE">Completó</option>
                <option value="NO-COMPLETE">No completó</option>
                <option value="N_PLANILLA">Sin planilla</option>
                <option value="CORREO">Sin correo</option>
                <option value="FASE">Sin fase</option>
                <option value="PARROQUIA">Sin parroquia</option>
                <option value="GRUPO">Sin grupo</option>
                <option value="PROFESION">Sin profesion</option>
                <option value="FECHA_NACIMIENTO">
                  Sin fecha de nacimiento
                </option>
                <option value="CEDULA">Sin cédula</option>
                <option value="PANADERIA-COMERCIAL">Sin profesion</option>
              </select>
              <button
                type="button"
                onClick={searchButton}
                className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Buscar
              </button>
            </div>
          </div>
        </header>

        <main>
          <div>
            <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
              <div className="px-4 py-6 sm:px-0">
                <div className="text-center my-4">
                  {" "}
                  {filterCount ? (
                    <>
                      <p>Se han encontrado: {filterCount} participante(s)</p>
                    </>
                  ) : (
                    "Sin resultados."
                  )}{" "}
                </div>

                <div>
                  <div className="overflow-x-auto relative">
                    <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                      <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                          <th scope="col" className="py-3 px-6">
                            NOMBRE Y APELLIDO
                          </th>
                          <th scope="col" className="py-3 px-6">
                            CÉDULA DE IDENTIDAD
                          </th>
                          <th scope="col" className="py-3 px-6">
                            PLANILLA
                          </th>
                          <th scope="col" className="py-3 px-6">
                            TALLER
                          </th>
                          <th scope="col" className="py-3 px-6">
                            ASISTIÓ
                          </th>
                          <th scope="col" className="py-3 px-6">
                            FASE
                          </th>
                          <th scope="col" className="py-3 px-6">
                            GRUPO/SECCIÓN
                          </th>
                          <th scope="col" className="py-3 px-6">
                            ACCIONAR
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {totalUsersNotPlanilla.map((user) => (
                          <>
                            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                              <th
                                scope="row"
                                className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                              >
                                {user.NOMBRE_APELLIDO}
                              </th>
                              <td className="py-4 px-6">{user.CEDULA}</td>
                              <td className="py-4 px-6">{user.N_PLANILLA}</td>
                              <td className="py-4 px-6">{user.TALLER}</td>
                              <td className="py-4 px-6">
                                {user.ATTENDED ? "SI" : "NO"}
                              </td>
                              <td className="py-4 px-6">
                                {user.FASE ? (
                                  user.FASE
                                ) : (
                                  <>
                                    <span className="text-red-200">
                                      Sin asignar
                                    </span>
                                  </>
                                )}
                              </td>
                              <td className="py-4 px-6">
                                {user.GRUPO ? (
                                  user.GRUPO
                                ) : (
                                  <>
                                    <span className="text-red-200">
                                      Sin asignar
                                    </span>
                                  </>
                                )}
                              </td>
                              <td className="py-4 px-6">
                                <a href={"/edit/" + user.CEDULA}>Editar</a>
                              </td>
                            </tr>
                          </>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Filters;
